name: Upload Video from Pixabay to YouTube

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the 'main' branch

jobs:
  upload_video:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the environment

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify the version you prefer

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

    - name: Run upload script
      run: |
        # Download the video from Pixabay and upload it to YouTube
        python upload_from_url_to_youtube.py

    - name: Commit the changes (optional)
      run: |
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Automated video upload from Pixabay to YouTube"
        git push
