name: Upload Video from Pixabay to YouTube

on:
  schedule:
    # This will run the workflow at 8 AM, 12 PM, and 6 PM UTC
    - cron: "0 8 * * *"   # 8:00 AM UTC (Morning)
    - cron: "0 12 * * *"  # 12:00 PM UTC (Lunchtime)
    - cron: "0 18 * * *"  # 6:00 PM UTC (Evening)
  push:
    branches:
      - main  # Optional: Trigger on push to 'main' branch as well (if you want)

jobs:
  upload_video:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the environment

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify the version you prefer

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

    - name: Run upload script
      run: |
        # Download the video from Pixabay and upload it to YouTube
        python upload_from_url_to_youtube.py

    - name: Commit the changes (optional)
      run: |
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Automated video upload from Pixabay to YouTube"
        git push
