name: Upload Video from Pixabay to YouTube

on:
  schedule:
    - cron: "0 8 * * *"   # 8:00 AM UTC (Morning)
    - cron: "0 12 * * *"  # 12:00 PM UTC (Lunchtime)
    - cron: "0 18 * * *"  # 6:00 PM UTC (Evening)
  workflow_dispatch:  # Allow manual trigger via "Run workflow" button

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

    - name: Run upload script
      run: |
        python upload_from_url_to_youtube.py

    - name: Log upload success
      run: |
        echo "Video uploaded successfully at $(date)" >> upload_log.txt
        git config --global user.name 'Your GitHub Username'
        git config --global user.email 'your-email@example.com'
        git add upload_log.txt
        # Authenticate using the GitHub token for pushing changes
        git commit -m "Log video upload timestamp"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
