name: Upload Video from Pixabay to YouTube

on:
  schedule:
    - cron: "0 8 * * *"   # 8:00 AM UTC (Morning)
    - cron: "0 12 * * *"  # 12:00 PM UTC (Lunchtime)
    - cron: "0 18 * * *"  # 6:00 PM UTC (Evening)
  workflow_dispatch:  # Allow manual trigger via "Run workflow" button

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Disable default GitHub token (GITHUB_TOKEN)

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

    - name: Run upload script
      run: python upload_from_url_to_youtube.py

    - name: Configure Git and Push Log
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        echo "Video uploaded successfully at $(date)" >> upload_log.txt
        git add upload_log.txt
        git commit -m "Log video upload timestamp" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
